{% set name = "lightrag-hku" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightrag_hku-{{ version }}.tar.gz
  sha256: cfc8c023db192e0204b80f82bd0c0cf99d670fbfaaeba7e7d27b20c1d85cf3b7
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - aioboto3
    - ollama
    - pyvis
    - python >={{ python_min }}
    - accelerate
    - ollama-python
    - openai
    - tiktoken
    - networkx
    - graspologic
    - nano-vectordb
    - hnswlib
    - python-xxhash
    - pytorch
    - tenacity
    - transformers
    - neo4j-python-driver
    - oracledb

test:
  imports:
    - lightrag
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/HKUDS/LightRAG
  summary: 'LightRAG: Simple and Fast Retrieval-Augmented Generation'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
