{% set name = "lightrag-hku" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightrag_hku-{{ version }}.tar.gz
  sha256: cb7028a5cb94379925f898b0b9f098e689ef7f31d360cc0740b13c5f7b1bb5df
  patches:
    - requirements.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - aioboto3
    - ollama
    - pyvis
    - python >=3.9
    - accelerate
    - ollama-python
    - openai
    - tiktoken
    - networkx
    - graspologic
    - nano-vectordb
    - hnswlib
    - python-xxhash
    - pytorch
    - tenacity
    - transformers
    - neo4j-python-driver
    - oracledb

test:
  imports:
    - lightrag
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HKUDS/LightRAG
  summary: 'LightRAG: Simple and Fast Retrieval-Augmented Generation'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
